Starting numpy library

In [2]:
import numpy as np

np.__version__

'2.5.1'

In [18]:
arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4 5 6 7 8]
1
(8,)


In [19]:
arr2 = np.array ([[1,3,5],[2,4,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 3 5]
 [2 4 6]]
2
(2, 3)


In [17]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
